# Generated by Django 4.2.19 on 2025-03-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='estado',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='estado_mensaje',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('RESPONDIDO', 'Respondido'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10, verbose_name='Estado del Mensaje'),
        ),
    ]
