services:
  - type: web
    name: libreria-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      bash backend/init_script.sh
    startCommand: cd backend && gunicorn config.wsgi:application --preload --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        value: ${DJANGO_SECRET_KEY}
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "proyecto-libreria-k9xr.onrender.com,localhost,127.0.0.1"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PYTHONPATH
        value: "backend"
    autoDeploy: true

