services:
  - type: web
    name: backend
    runtime: python
    buildCommand: pip install -r backend/config/requirements.txt
    startCommand: cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
