# Generated by Django 4.2.20 on 2025-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuariopreferencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
