# Generated by Django 4.2.20 on 2025-04-30 05:50

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_tokenrecuperacionpassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariopreferencias",
            name="preferencias",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="foto_perfil",
            field=models.ImageField(
                blank=True,
                help_text="Foto de perfil (formatos: JPG, PNG, WebP)",
                null=True,
                upload_to="perfiles/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
    ]
