# Generated by Django 4.2.20 on 2025-04-30 07:57

import apps.usuarios.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuariopreferencias_preferencias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil (formatos: JPG, PNG, WebP)', null=True, upload_to=apps.usuarios.models.user_profile_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
