# Generated by Django 4.2.21 on 2025-06-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la categoría', null=True),
        ),
    ]
