# Generated by Django 4.2.21 on 2025-06-08 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría del libro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libros.categoria'),
        ),
    ]
