# Generated by Django 4.2.19 on 2025-03-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='estado',
        ),
        migrations.AddField(
            model_name='noticia',
            name='estado_noticia',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=10, verbose_name='Estado de la Noticia'),
        ),
    ]
