# Generated by Django 4.2.20 on 2025-05-23 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0001_initial"),
        ("compras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoLibro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="libros.libro"
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compras.pedidos",
                    ),
                ),
            ],
            options={
                "unique_together": {("pedido", "libro")},
            },
        ),
    ]
