# Generated by Django 4.2.21 on 2025-05-21 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0001_initial'),
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historial',
            name='libros',
            field=models.ManyToManyField(blank=True, related_name='historiales', to='libros.libro'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='libros',
            field=models.ManyToManyField(blank=True, related_name='carritos', to='libros.libro'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
