# Generated by Django 4.2.20 on 2025-04-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Cancelado', 'Cancelado')], default='Activa', max_length=10),
        ),
    ]
