# Generated by Django 4.2.20 on 2025-06-05 17:33

import apps.compras.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("compras", "0002_pedidolibro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("fecha_reserva", models.DateTimeField(auto_now_add=True)),
                (
                    "fecha_expiracion",
                    models.DateTimeField(
                        default=apps.compras.models.default_expiracion
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="libros.libro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Prestamo",
        ),
    ]
