# Generated by Django 4.2.20 on 2025-06-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0003_reserva_delete_prestamo"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Reservado", "Reservado"),
                    ("Cancelado", "Cancelado"),
                    ("Expirado", "Expirado"),
                ],
                default="Reservado",
                max_length=10,
            ),
        ),
    ]
