# Generated by Django 4.2.20 on 2025-06-05 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("compras", "0004_reserva_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialDeCompras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="pedidos",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Cancelado", "Cancelado"),
                    ("En Proceso", "En Proceso"),
                    ("Entregado", "Entregado"),
                ],
                default="Pendiente",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Completado", "Completado"),
                    ("Reservado", "Reservado"),
                    ("Cancelado", "Cancelado"),
                    ("Expirado", "Expirado"),
                ],
                default="Reservado",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Historial",
        ),
        migrations.AddField(
            model_name="historialdecompras",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_compras",
                to="compras.pedidos",
            ),
        ),
        migrations.AddField(
            model_name="historialdecompras",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_compras",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
